name: 'main'

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#     - name: test test
#       uses: ./test/
    - name: linux test
      uses: ./
      id: hello
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@0.0.15
      with: 
        required-ros-distributions: eloquent
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
