name: 'main'

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
#     - name: Checkout
#       uses: actions/checkout@v2
#     - name: test test
#       uses: ./test/
#     - name: linux test
#       uses: ./
#       id: hello
    - name: exp
      run: export
#     - name: Setup ROS2
#       uses: ros-tooling/setup-ros@0.0.15
#       with: 
#           required-ros-distributions: eloquent
    - uses: ros-tooling/setup-ros@0.0.11
      with:
        required-ros-distributions: melodic dashing
    - run: "source /opt/ros/dashing/setup.bash && ros run --help"
#     - name: ls3
#       run: "source /opt/ros/eloquent/setup.bash"    
    - name: exp
      run: export
    - name: ls
      run: ls -R
    - name: ls
      run: pwd
#     - name: ros2setupbash
#       run: cd ..
#     - name: ls1
#       run: ls
#     - name: cd1
#       run: cd ..
#     - name: ls2
#       run: ls
#     - name: cd2
#       run: cd eloquent    
#     - name: Run Tests
#       uses: ros-tooling/action-ros-ci@0.0.13
#       with:
#         package-name: example_package

#     - name: Upload Logs
#       uses: actions/upload-artifact@v1
#       with:
#         name: colcon-logs
#         path: ros_ws/log
#       if: always()
#     - name: cd
#       uses: cd /opt/
    - name: run doctor
      run: ros2 doctor --report
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
