name: 'main'

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#     - name: test test
#       uses: ./test/
#     - name: linux test
#       uses: ./
#       id: hello
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@0.0.15
      with: 
        required-ros-distributions: eloquent
    - name: ros2setupbash
      run: cd /opt/
#       source /opt/ros/eloquent/setup.bash        
#     - name: Run Tests
#       uses: ros-tooling/action-ros-ci@0.0.13
#       with:
#         package-name: example_package

#     - name: Upload Logs
#       uses: actions/upload-artifact@v1
#       with:
#         name: colcon-logs
#         path: ros_ws/log
#       if: always()
#     - name: cd
#       uses: cd /opt/
#     - name: run doctor
#       run: ros2 doctor --report
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
